// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB910KH3jgiLM5iASL6R0-J99mpixFb9Ug',
    appId: '1:960632255513:web:12ab6e1eb8bad8d6c16688',
    messagingSenderId: '960632255513',
    projectId: 'buddingfinance-674bf',
    authDomain: 'buddingfinance-674bf.firebaseapp.com',
    storageBucket: 'buddingfinance-674bf.firebasestorage.app',
    measurementId: 'G-3927QKJ7CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVS7KpghWNzFfXGqr7JxtZfXpd_fjW8o',
    appId: '1:960632255513:android:731d286280cc9cacc16688',
    messagingSenderId: '960632255513',
    projectId: 'buddingfinance-674bf',
    storageBucket: 'buddingfinance-674bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMMVBySMuY948q4XPEHbuNizLkvwMHbdI',
    appId: '1:960632255513:ios:96462ea2fd550041c16688',
    messagingSenderId: '960632255513',
    projectId: 'buddingfinance-674bf',
    storageBucket: 'buddingfinance-674bf.firebasestorage.app',
    iosBundleId: 'com.dagemabraham.buddingfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMMVBySMuY948q4XPEHbuNizLkvwMHbdI',
    appId: '1:960632255513:ios:1400c30bca673aeac16688',
    messagingSenderId: '960632255513',
    projectId: 'buddingfinance-674bf',
    storageBucket: 'buddingfinance-674bf.firebasestorage.app',
    iosBundleId: 'com.example.buddingfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB910KH3jgiLM5iASL6R0-J99mpixFb9Ug',
    appId: '1:960632255513:web:dacff7e039d10dc9c16688',
    messagingSenderId: '960632255513',
    projectId: 'buddingfinance-674bf',
    authDomain: 'buddingfinance-674bf.firebaseapp.com',
    storageBucket: 'buddingfinance-674bf.firebasestorage.app',
    measurementId: 'G-39X9H5V5LE',
  );

}